kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-pvc
  namespace: airflow-on-k8s
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: logs-pv
  storageClassName: ""